import "%modules%/header/header";
import "%modules%/footer/footer";
import "%modules%/promo/promo";
import "%modules%/aside/aside";
import "%modules%/modal/modal";
import "%modules%/diploms/diploms";
import "%modules%/reviews/reviews";
import "%modules%/formats/formats";
import "%modules%/feed-form/feed-form";
